<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="CSOSTAR0664D" name="org.angelLiteApp.android.Tests.CalculatorTest" tests="7" failures="1" timestamp="28 Feb 2020 06:46:10 GMT" time="41.555" errors="0">
  <testcase name="addition_Of_Two_Number" time="4.494" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
  <testcase name="addition_Of_Three_Number" time="6.725" classname="org.angelLiteApp.android.Tests.CalculatorTest">
    <failure type="java.lang.AssertionError" message="The following asserts failed:
	calculated result is not correct expected [= 20] but found [= 22]">
      <![CDATA[java.lang.AssertionError: The following asserts failed:
calculated result is not correct expected [= 20] but found [= 22]
at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:43)
at org.angelLiteApp.android.Tests.CalculatorTest.addition_Of_Three_Number(CalculatorTest.java:61)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:580)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:716)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:988)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:114)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- addition_Of_Three_Number -->
  <testcase name="substraction" time="5.529" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
  <testcase name="multiplication_Of_Two_Number" time="5.689" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
  <testcase name="multiplication_Of_Three_Number" time="7.071" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
  <testcase name="division" time="5.338" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
  <testcase name="multiple_Operation" time="6.709" classname="org.angelLiteApp.android.Tests.CalculatorTest"/>
</testsuite> <!-- org.angelLiteApp.android.Tests.CalculatorTest -->
